# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
      labels:
        exporter: 'prometheus'
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['localhost:8080']
      labels:
        exporter: 'cadvisor'
  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']
      labels:
        ec2_name: 'flask'
        exporter: 'node'